[package]
name = "vs-filters"
version = "1.0.0"
authors = ["quietvoid"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vapoursynth = { version = "0.3.0", features = ["vapoursynth-api-36"] }
failure = "0.1.8"
image = "0.23.14"
itertools = "0.10.1"
dolby_vision = "1.3.1"
anyhow = "1.0.51"
hevc_parser = "0.3.0"

[lib]
crate-type = ["cdylib"]
