[package]
name = "vs-nlq"
version = "1.1.0"
authors = ["quietvoid"]
edition = "2021"
rust-version = "1.61.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vapoursynth = { version = "0.4.0", features = ["vapoursynth-api-36", "vapoursynth-functions"] }
dolby_vision = "3.1.2"
image = "0.24.6"
itertools = "0.10.5"
anyhow = "1.0.71"
rayon = "1.7.0"

[lib]
crate-type = ["cdylib"]
