[package]
name = "vs-nlq"
version = "1.1.0"
authors = ["quietvoid"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vapoursynth = { git = "https://github.com/YaLTeR/vapoursynth-rs.git", features = ["vapoursynth-api-36", "vapoursynth-functions"] }
image = "0.24.2"
itertools = "0.10.3"
dolby_vision = "1.6.7"
anyhow = "1.0.58"
rayon = "1.5.3"

[lib]
crate-type = ["cdylib"]
